# -*- coding: utf-8 -*-
"""Part-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_IQLZoLQgyPWcG7rnH4L2nBpgqASFrv
"""

import pandas as pd

# Amazon items
items = {
    1: "A Beginner’s Guide",
    2: "Java: The Complete Reference",
    3: "Java For Dummies",
    4: "Android Programming: The Big Nerd Ranch",
    5: "Head First Java 2nd Edition",
    6: "Beginning Programming with Java",
    7: "Java 8 Pocket Guide",
    8: "C++ Programming in Easy Steps",
    9: "Effective Java (2nd Edition)",
    10: "HTML and CSS: Design and Build Websites"
}

# Transaction data
transactions = {
    "Trans1": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "Android Programming: The Big Nerd Ranch"],
    "Trans2": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies"],
    "Trans3": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "Android Programming: The Big Nerd Ranch", "Head First Java 2nd Edition"],
    "Trans4": ["Android Programming: The Big Nerd Ranch", "Head First Java 2nd Edition", "Beginning Programming with Java"],
    "Trans5": ["Android Programming: The Big Nerd Ranch", "Beginning Programming with Java", "Java 8 Pocket Guide"],
    "Trans6": ["A Beginner’s Guide", "Android Programming: The Big Nerd Ranch", "Head First Java 2nd Edition"],
    "Trans7": ["A Beginner’s Guide", "Head First Java 2nd Edition", "Beginning Programming with Java"],
    "Trans8": ["Java: The Complete Reference", "Java For Dummies", "Android Programming: The Big Nerd Ranch"],
    "Trans9": ["Java For Dummies", "Android Programming: The Big Nerd Ranch", "Head First Java 2nd Edition", "Beginning Programming with Java"],
    "Trans10": ["Beginning Programming with Java", "Java 8 Pocket Guide", "C++ Programming in Easy Steps"],
    "Trans11": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "Android Programming: The Big Nerd Ranch"],
    "Trans12": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "HTML and CSS: Design and Build Websites"],
    "Trans13": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "Java 8 Pocket Guide", "HTML and CSS: Design and Build Websites"],
    "Trans14": ["Java For Dummies", "Android Programming: The Big Nerd Ranch", "Head First Java 2nd Edition"],
    "Trans15": ["Java For Dummies", "Android Programming: The Big Nerd Ranch"],
    "Trans16": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "Android Programming: The Big Nerd Ranch"],
    "Trans17": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies", "Android Programming: The Big Nerd Ranch"],
    "Trans18": ["Head First Java 2nd Edition", "Beginning Programming with Java", "Java 8 Pocket Guide"],
    "Trans19": ["Android Programming: The Big Nerd Ranch", "Head First Java 2nd Edition"],
    "Trans20": ["A Beginner’s Guide", "Java: The Complete Reference", "Java For Dummies"]
}

# Convert dictionary to DataFrame
df_items = pd.DataFrame(list(items.items()), columns=["Item #", "Item Name"])
df_transactions = pd.DataFrame(list(transactions.items()), columns=["Transaction ID", "Transaction"])

# Save to CSV files
df_items.to_csv("amazon_items.csv", index=False)
df_transactions.to_csv("amazon_transactions.csv", index=False)

import pandas as pd

# Best Buy items
items = {
    1: "Digital Camera",
    2: "Lab Top",
    3: "Desk Top",
    4: "Printer",
    5: "Flash Drive",
    6: "Microsoft Office",
    7: "Speakers",
    8: "Lab Top Case",
    9: "Anti-Virus",
    10: "External Hard Drive"
}

# Transaction data
transactions = {
    "Trans1": ["Desk Top", "Printer", "Flash Drive", "Microsoft Office", "Speakers", "Anti-Virus"],
    "Trans2": ["Lab Top", "Flash Drive", "Microsoft Office", "Lab Top Case", "Anti-Virus"],
    "Trans3": ["Lab Top", "Printer", "Flash Drive", "Microsoft Office", "Anti-Virus", "Lab Top Case", "External Hard Drive"],
    "Trans4": ["Lab Top", "Printer", "Flash Drive", "Anti-Virus", "External Hard Drive", "Lab Top Case"],
    "Trans5": ["Lab Top", "Flash Drive", "Lab Top Case", "Anti-Virus"],
    "Trans6": ["Lab Top", "Printer", "Flash Drive", "Microsoft Office"],
    "Trans7": ["Desk Top", "Printer", "Flash Drive", "Microsoft Office"],
    "Trans8": ["Lab Top", "External Hard Drive", "Anti-Virus"],
    "Trans9": ["Desk Top", "Printer", "Flash Drive", "Microsoft Office", "Lab Top Case", "Anti-Virus", "Speakers", "External Hard Drive"],
    "Trans10": ["Digital Camera", "Lab Top", "Desk Top", "Printer", "Flash Drive", "Microsoft Office", "Lab Top Case", "Anti-Virus", "External Hard Drive", "Speakers"],
    "Trans11": ["Lab Top", "Desk Top", "Lab Top Case", "External Hard Drive", "Speakers", "Anti-Virus"],
    "Trans12": ["Digital Camera", "Lab Top", "Lab Top Case", "External Hard Drive", "Anti-Virus", "Speakers"],
    "Trans13": ["Digital Camera", "Speakers"],
    "Trans14": ["Digital Camera", "Desk Top", "Printer", "Flash Drive", "Microsoft Office"],
    "Trans15": ["Printer", "Flash Drive", "Microsoft Office", "Anti-Virus", "Lab Top Case", "Speakers", "External Hard Drive"],
    "Trans16": ["Digital Camera", "Flash Drive", "Microsoft Office", "Anti-Virus", "Lab Top Case", "External Hard Drive", "Speakers"],
    "Trans17": ["Digital Camera", "Lab Top", "Lab Top Case"],
    "Trans18": ["Digital Camera", "Lab Top Case", "Speakers"],
    "Trans19": ["Digital Camera", "Lab Top", "Printer", "Flash Drive", "Microsoft Office", "Speakers", "Lab Top Case", "Anti-Virus"],
    "Trans20": ["Digital Camera", "Lab Top", "Speakers", "Anti-Virus", "Lab Top Case"]
}

# Convert dictionary to DataFrame
df_items = pd.DataFrame(list(items.items()), columns=["Item #", "Item Name"])
df_transactions = pd.DataFrame(list(transactions.items()), columns=["Transaction ID", "Transaction"])

# Save to CSV files
df_items.to_csv("best_buy_items.csv", index=False)
df_transactions.to_csv("best_buy_transactions.csv", index=False)

import pandas as pd

# K-mart items
items = {
    1: "Quilts",
    2: "Bedspreads",
    3: "Decorative Pillows",
    4: "Bed Skirts",
    5: "Sheets",
    6: "Shams",
    7: "Bedding Collections",
    8: "Kids Bedding",
    9: "Embroidered Bedspread",
    10: "Towels"
}

# Transaction data
transactions = {
    "Trans1": ["Decorative Pillows", "Quilts", "Embroidered Bedspread"],
    "Trans2": ["Embroidered Bedspread", "Shams", "Kids Bedding", "Bedding Collections", "Bed Skirts", "Bedspreads", "Sheets"],
    "Trans3": ["Decorative Pillows", "Quilts", "Embroidered Bedspread", "Shams", "Kids Bedding", "Bedding Collections"],
    "Trans4": ["Kids Bedding", "Bedding Collections", "Sheets", "Bedspreads", "Bed Skirts"],
    "Trans5": ["Decorative Pillows", "Kids Bedding", "Bedding Collections", "Sheets", "Bed Skirts", "Bedspreads"],
    "Trans6": ["Bedding Collections", "Bedspreads", "Bed Skirts", "Sheets", "Shams", "Kids Bedding"],
    "Trans7": ["Decorative Pillows", "Quilts"],
    "Trans8": ["Decorative Pillows", "Quilts", "Embroidered Bedspread"],
    "Trans9": ["Bedspreads", "Bed Skirts", "Shams", "Kids Bedding", "Sheets"],
    "Trans10": ["Quilts", "Embroidered Bedspread", "Bedding Collections"],
    "Trans11": ["Bedding Collections", "Bedspreads", "Bed Skirts", "Kids Bedding", "Shams", "Sheets"],
    "Trans12": ["Decorative Pillows", "Quilts"],
    "Trans13": ["Embroidered Bedspread", "Shams"],
    "Trans14": ["Sheets", "Shams", "Bed Skirts", "Kids Bedding"],
    "Trans15": ["Decorative Pillows", "Quilts"],
    "Trans16": ["Decorative Pillows", "Kids Bedding", "Bed Skirts", "Shams"],
    "Trans17": ["Decorative Pillows", "Shams", "Bed Skirts"],
    "Trans18": ["Quilts", "Sheets", "Kids Bedding"],
    "Trans19": ["Shams", "Bed Skirts", "Kids Bedding", "Sheets"],
    "Trans20": ["Decorative Pillows", "Bedspreads", "Shams", "Sheets", "Bed Skirts", "Kids Bedding"]
}

# Convert dictionary to DataFrame
df_items = pd.DataFrame(list(items.items()), columns=["Item #", "Item Name"])
df_transactions = pd.DataFrame(list(transactions.items()), columns=["Transaction ID", "Transaction"])

# Save to CSV files
df_items.to_csv("k_mart_items.csv", index=False)
df_transactions.to_csv("k_mart_transactions.csv", index=False)

import pandas as pd

# Nike items
items = {
    1: "Running Shoe",
    2: "Soccer Shoe",
    3: "Socks",
    4: "Swimming Shirt",
    5: "Dry Fit V-Nick",
    6: "Rash Guard",
    7: "Sweatshirts",
    8: "Hoodies",
    9: "Tech Pants",
    10: "Modern Pants"
}

# Transaction data
transactions = {
    "Trans1": ["Running Shoe", "Socks", "Sweatshirts", "Modern Pants"],
    "Trans2": ["Running Shoe", "Socks", "Sweatshirts"],
    "Trans3": ["Running Shoe", "Socks", "Sweatshirts", "Modern Pants"],
    "Trans4": ["Running Shoe", "Sweatshirts", "Modern Pants"],
    "Trans5": ["Running Shoe", "Socks", "Sweatshirts", "Modern Pants", "Soccer Shoe"],
    "Trans6": ["Running Shoe", "Socks", "Sweatshirts"],
    "Trans7": ["Running Shoe", "Socks", "Sweatshirts", "Modern Pants", "Tech Pants", "Rash Guard", "Hoodies"],
    "Trans8": ["Swimming Shirt", "Socks", "Sweatshirts"],
    "Trans9": ["Swimming Shirt", "Rash Guard", "Dry Fit V-Nick", "Hoodies", "Tech Pants"],
    "Trans10": ["Swimming Shirt", "Rash Guard", "Dry Fit V-Nick"],
    "Trans11": ["Swimming Shirt", "Rash Guard", "Dry Fit V-Nick"],
    "Trans12": ["Running Shoe", "Swimming Shirt", "Socks", "Sweatshirts", "Modern Pants", "Soccer Shoe", "Rash Guard", "Hoodies", "Tech Pants", "Dry Fit V-Nick"],
    "Trans13": ["Running Shoe", "Swimming Shirt", "Socks", "Sweatshirts", "Modern Pants", "Soccer Shoe", "Rash Guard", "Tech Pants", "Dry Fit V-Nick", "Hoodies"],
    "Trans14": ["Running Shoe", "Swimming Shirt", "Rash Guard", "Tech Pants", "Hoodies", "Dry Fit V-Nick"],
    "Trans15": ["Running Shoe", "Swimming Shirt", "Socks", "Sweatshirts", "Modern Pants", "Dry Fit V-Nick", "Rash Guard", "Tech Pants"],
    "Trans16": ["Swimming Shirt", "Soccer Shoe", "Hoodies", "Dry Fit V-Nick", "Tech Pants", "Rash Guard"],
    "Trans17": ["Running Shoe", "Socks"],
    "Trans18": ["Socks", "Sweatshirts", "Modern Pants", "Soccer Shoe", "Hoodies", "Rash Guard", "Tech Pants", "Dry Fit V-Nick"],
    "Trans19": ["Running Shoe", "Swimming Shirt", "Rash Guard"],
    "Trans20": ["Running Shoe", "Swimming Shirt", "Socks", "Sweatshirts", "Modern Pants", "Soccer Shoe", "Hoodies", "Tech Pants", "Rash Guard", "Dry Fit V-Nick"]
}

# Convert dictionary to DataFrame
df_items = pd.DataFrame(list(items.items()), columns=["Item #", "Item Name"])
df_transactions = pd.DataFrame(list(transactions.items()), columns=["Transaction ID", "Transaction"])

# Save to CSV files
df_items.to_csv("nike_items.csv", index=False)
df_transactions.to_csv("nike_transactions.csv", index=False)

import pandas as pd

# Flipkart items
items = {
    1: "Mobile Phones",
    2: "Laptops",
    3: "Televisions",
    4: "Washing Machines",
    5: "Refrigerators",
    6: "Air Conditioners",
    7: "Microwaves",
    8: "Printers",
    9: "Cameras",
    10: "Smart Watches"
}

# Transaction data
transactions = {
    "Trans1": ["Mobile Phones", "Laptops", "Cameras"],
    "Trans2": ["Laptops", "Televisions", "Washing Machines", "Refrigerators"],
    "Trans3": ["Mobile Phones", "Televisions", "Washing Machines"],
    "Trans4": ["Refrigerators", "Air Conditioners", "Microwaves"],
    "Trans5": ["Mobile Phones", "Cameras", "Printers", "Smart Watches"],
    "Trans6": ["Laptops", "Televisions", "Air Conditioners"],
    "Trans7": ["Mobile Phones", "Refrigerators", "Washing Machines"],
    "Trans8": ["Laptops", "Printers", "Cameras", "Smart Watches"],
    "Trans9": ["Televisions", "Washing Machines", "Refrigerators", "Microwaves"],
    "Trans10": ["Mobile Phones", "Air Conditioners", "Printers"],
    "Trans11": ["Laptops", "Televisions", "Refrigerators", "Microwaves", "Cameras"],
    "Trans12": ["Mobile Phones", "Air Conditioners", "Microwaves", "Smart Watches"],
    "Trans13": ["Televisions", "Washing Machines", "Refrigerators", "Printers", "Cameras"],
    "Trans14": ["Mobile Phones", "Air Conditioners", "Refrigerators", "Smart Watches"],
    "Trans15": ["Laptops", "Televisions", "Washing Machines", "Refrigerators", "Cameras", "Printers"],
    "Trans16": ["Mobile Phones", "Air Conditioners", "Microwaves", "Cameras", "Smart Watches"],
    "Trans17": ["Laptops", "Televisions", "Refrigerators", "Air Conditioners"],
    "Trans18": ["Mobile Phones", "Televisions", "Washing Machines", "Refrigerators"],
    "Trans19": ["Laptops", "Microwaves", "Cameras", "Printers", "Smart Watches"],
    "Trans20": ["Mobile Phones", "Refrigerators", "Air Conditioners", "Printers"]
}

# Convert dictionary to DataFrame
df_items = pd.DataFrame(list(items.items()), columns=["Item #", "Item Name"])
df_transactions = pd.DataFrame(list(transactions.items()), columns=["Transaction ID", "Transaction"])

# Save to CSV files
df_items.to_csv("flipkart_items.csv", index=False)
df_transactions.to_csv("flipkart_transactions.csv", index=False)